-- drop table if exists bootuser cascade;
create table bootuser (
	id int generated by default as identity primary key,
	username varchar(45) unique not null,
	name varchar(45),
	last_name varchar(45),
	password varchar(40) not null,
	email varchar(70) unique not null,
	profile_img varchar(100),
	registration_date date
);

-- drop table if exists bootuser_subscriber;
create table bootuser_subscriber(
	user_id int references bootUser(id) on delete cascade,
	subscriber_id int references bootUser(id) on delete cascade,
	primary key(user_id, subscriber_id),
	check(user_id <> subscriber_id)
);

-- drop table if exists post cascade;
create table post(
	id int generated by default as identity primary key,
	post_text text not null,
	created_date date,
	updated_date date,
	user_creator int references bootUser(id) on delete set null
);

-- drop table if exists comment;
create table comment(
	id int generated by default as identity primary key,
	comment_text text not null,
	created_date date,
	updated_date date,
	user_commentator int references bootUser(id) on delete set null,
	fk_post int references post(id) on delete cascade
);